---
title: "Descriptive Statistics and Data Analysis"
author: "Gracia Andriamiadana"
date: "02/08/2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(dplyr)
library(magrittr)
library(ggplot2)
library(lubridate)

setwd("/Users/BHCadmin/Documents/mres_gracia/")
```

## Load and edit data tables
```{r}
setwd("/Users/BHCadmin/Documents/mres_gracia/")

demographic_table <- read.csv("upd_demographics_table_UKB_data.tsv", header = T, sep = "\t")
cmr_measures_tbl <- read.csv("CMR_patients_in_UKB.tsv", header = T, sep = "\t")

diabetes_tbl = read.csv("updated_diabetes_tbl.tsv", sep = "\t")
hypertension_tbl = read.csv("updated_hypertension_tbl.tsv", sep = "\t")
cholesterol_tbl = read.csv("updated_cholesterol_tbl.tsv", sep = "\t")

IHD_tbl = read.csv("updated_IHD_tbl.tsv", sep = "\t")
non_IHD_tbl = read.csv("updated_non_IHD_tbl.tsv", sep = "\t")
HF_tbl = read.csv("updated_HF_tbl.tsv", sep = "\t")
HA_tbl = read.csv("updated_HA_tbl.tsv", sep = "\t")
pericardial_tbl <- read.csv("updated_pericardial_tbl.tsv", sep = "\t")
stroke_tbl = read.csv("updated_stroke_tbl.tsv", sep = "\t")

BC_tbl <- read.csv("updated_BC_tbl.tsv", sep = "\t", header = T)
BC_ids <- BC_tbl %>% dplyr::filter(BC_status == 1) %>% select(f.eid)
nrow(BC_ids)
BC_ids <- as.vector(BC_ids$f.eid)

non_BC_ids <- BC_tbl %>% dplyr::filter(BC_status == 0) %>% select(f.eid)
nrow(non_BC_ids)
non_BC_ids <- as.vector(non_BC_ids$f.eid)

RT_tbl <- read.csv("updated_RT_tbl.tsv", sep = "\t", header = T)
RT_ids <- RT_tbl %>% dplyr::filter(RT_status == 1) %>% select(f.eid)
nrow(RT_ids)

RT_and_BC_ids <- intersect(as.vector(BC_ids), as.vector(RT_ids$f.eid))
length(RT_and_BC_ids)

no_RT_ids <- RT_tbl %>% dplyr::filter(RT_status == 0) %>% select(f.eid)
no_RT_and_BC_ids <- intersect(as.vector(BC_ids), as.vector(no_RT_ids$f.eid))
length(no_RT_and_BC_ids)

cmr_ids <- cmr_measures_tbl$f.eid
cmr_no_bc_ids <- intersect(cmr_ids, non_BC_ids)
length(cmr_no_bc_ids)

cmr_bc_ids <- intersect(cmr_ids, BC_ids)
length(cmr_bc_ids)

cmr_bc_rt_ids <- intersect(cmr_ids, RT_and_BC_ids)
length(cmr_bc_rt_ids)

cmr_bc_but_no_mrt <- intersect(cmr_ids, no_RT_and_BC_ids)
length(cmr_bc_but_no_mrt)

sample_df <- read.csv("analysis_sample_UKB_patients.tsv", sep = "\t")
```


## Baseline Characteristics of Whole and Sub Samples

### CVDs

```{r whole_sample_CVDs}
paste("Prevelant Cases of Pericardial Disease:", sum(pericardial_tbl$prevalent_status))
paste("Incident Cases of Pericardial Disease:", sum(pericardial_tbl$incident_status))

paste("Prevelant Cases of MYO INF:", sum(HA_tbl$prevalent_status))
paste("Incident Cases of HYO INF:", sum(HA_tbl$incident_status))

paste("Prevelant Cases of HF:", sum(HF_tbl$prevalent_status))
paste("Incident Cases of HF:", sum(HF_tbl$incident_status))

paste("Prevelant Cases of STROKE:", sum(stroke_tbl$prevalent_status))
paste("Incident Cases of STROKE:", sum(stroke_tbl$incident_status))

paste("Prevelant Cases of IHD:", sum(IHD_tbl$prevalent_status))
paste("Incident Cases of IHD:", sum(IHD_tbl$incident_status))

paste("Prevelant Cases of NICM:", sum(non_IHD_tbl$prevalent_status))
paste("Incident Cases of NICM:", sum(non_IHD_tbl$incident_status))

cat("No of diabetes patients in whole sample:", sum(sample_df$diabetes_status), "\n")
cat("No of hypertension patients in whole sample:", sum(sample_df$hypertension_status), "\n")
cat("No of cholesterol patients in whole sample:", sum(sample_df$cholesterol_status), "\n")

continuous <-select_if(demographic_table, is.numeric)
summary(continuous)

```

```{r BC_sample_CVDs}
stroke_tbl_BC <- stroke_tbl %>% dplyr::filter(f.eid %in% BC_ids)
IHD_tbl_BC <- IHD_tbl %>% dplyr::filter(f.eid %in% BC_ids)
NICM_tbl_BC <- non_IHD_tbl %>% dplyr::filter(f.eid %in% BC_ids) 
pericard_tbl_BC <- pericardial_tbl %>% dplyr::filter(f.eid %in% BC_ids)
HF_tbl_BC <- HF_tbl %>% dplyr::filter(f.eid %in% BC_ids)
myocard_tbl_BC <- HA_tbl %>% dplyr::filter(f.eid %in% BC_ids)
diabetes_tbl_BC <- diabetes_tbl %>% dplyr::filter(f.eid %in% BC_ids) 
cholesterol_tbl_BC <- cholesterol_tbl %>% dplyr::filter(f.eid %in% BC_ids)
hypertension_tbl_BC <- hypertension_tbl %>% dplyr::filter(f.eid %in% BC_ids)
  
paste("Prevelant Cases of Pericardial Disease:", sum(pericard_tbl_BC$prevalent_status))
paste("Incident Cases of Pericardial Disease:", sum(pericard_tbl_BC$incident_status))

paste("Prevelant Cases of MYO INF:", sum(myocard_tbl_BC$prevalent_status))
paste("Incident Cases of MYO INF:", sum(myocard_tbl_BC$incident_status))

paste("Prevelant Cases of HF:", sum(HF_tbl_BC$prevalent_status))
paste("Incident Cases of HF:", sum(HF_tbl_BC$incident_status))

paste("Prevelant Cases of STROKE:", sum(stroke_tbl_BC$prevalent_status))
paste("Incident Cases of STROKE:", sum(stroke_tbl_BC$incident_status))

paste("Prevelant Cases of IHD:", sum(IHD_tbl_BC$prevalent_status))
paste("Incident Cases of IHD:", sum(IHD_tbl_BC$incident_status))

paste("Prevelant Cases of NICM:", sum(NICM_tbl_BC$prevalent_status))
paste("Incident Cases of NICM:", sum(NICM_tbl_BC$incident_status))

cat("No of diabetes patients in whole sample:", sum(diabetes_tbl_BC$diabetes_status), "\n")
cat("No of hypertension patients in whole sample:", sum(hypertension_tbl_BC$hypertension_status), "\n")
cat("No of cholesterol patients in whole sample:", sum(cholesterol_tbl_BC$cholesterol_status), "\n")
```

```{r BC_and_MRT_sample_CVDs}
stroke_tbl_BC <- stroke_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
IHD_tbl_BC <- IHD_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
NICM_tbl_BC <- non_IHD_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids) 
pericard_tbl_BC <- pericardial_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
HF_tbl_BC <- HF_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
myocard_tbl_BC <- HA_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
diabetes_tbl_BC <- diabetes_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids) 
cholesterol_tbl_BC <- cholesterol_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
hypertension_tbl_BC <- hypertension_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
  
paste("Prevelant Cases of Pericardial Disease:", sum(pericard_tbl_BC$prevalent_status))
paste("Incident Cases of Pericardial Disease:", sum(pericard_tbl_BC$incident_status))

paste("Prevelant Cases of MYO INF:", sum(myocard_tbl_BC$prevalent_status))
paste("Incident Cases of MYO INF:", sum(myocard_tbl_BC$incident_status))

paste("Prevelant Cases of HF:", sum(HF_tbl_BC$prevalent_status))
paste("Incident Cases of HF:", sum(HF_tbl_BC$incident_status))

paste("Prevelant Cases of STROKE:", sum(stroke_tbl_BC$prevalent_status))
paste("Incident Cases of STROKE:", sum(stroke_tbl_BC$incident_status))

paste("Prevelant Cases of IHD:", sum(IHD_tbl_BC$prevalent_status))
paste("Incident Cases of IHD:", sum(IHD_tbl_BC$incident_status))

paste("Prevelant Cases of NICM:", sum(NICM_tbl_BC$prevalent_status))
paste("Incident Cases of NICM:", sum(NICM_tbl_BC$incident_status))

cat("No of diabetes patients in whole sample:", sum(diabetes_tbl_BC$diabetes_status), "\n")
cat("No of hypertension patients in whole sample:", sum(hypertension_tbl_BC$hypertension_status), "\n")
cat("No of cholesterol patients in whole sample:", sum(cholesterol_tbl_BC$cholesterol_status), "\n")
```

```{r CMR_sample_CVDs}

pericard_tbl_BC <- pericardial_tbl %>% filter(f.eid %in% cmr_ids)
stroke_tbl_BC <- stroke_tbl %>% filter(f.eid %in% cmr_ids)
myocard_tbl_BC <- HA_tbl %>% filter(f.eid %in% cmr_ids)
HF_tbl_BC <- HF_tbl %>% filter(f.eid %in% cmr_ids)
IHD_tbl_BC <- IHD_tbl %>% filter(f.eid %in% cmr_ids)
NICM_tbl_BC <- non_IHD_tbl %>% filter(f.eid %in% cmr_ids)
diabetes_tbl_BC <- diabetes_tbl %>% dplyr::filter(f.eid %in% cmr_ids) 
cholesterol_tbl_BC <- cholesterol_tbl %>% dplyr::filter(f.eid %in% cmr_ids)
hypertension_tbl_BC <- hypertension_tbl %>% dplyr::filter(f.eid %in% cmr_ids)
 
paste("Prevelant Cases of Pericardial Disease:", sum(pericard_tbl_BC$prevalent_status))
paste("Incident Cases of Pericardial Disease:", sum(pericard_tbl_BC$incident_status))

paste("Prevelant Cases of MYO INF:", sum(myocard_tbl_BC$prevalent_status))
paste("Incident Cases of MYO INF:", sum(myocard_tbl_BC$incident_status))

paste("Prevelant Cases of HF:", sum(HF_tbl_BC$prevalent_status))
paste("Incident Cases of HF:", sum(HF_tbl_BC$incident_status))

paste("Prevelant Cases of STROKE:", sum(stroke_tbl_BC$prevalent_status))
paste("Incident Cases of STROKE:", sum(stroke_tbl_BC$incident_status))

paste("Prevelant Cases of IHD:", sum(IHD_tbl_BC$prevalent_status))
paste("Incident Cases of IHD:", sum(IHD_tbl_BC$incident_status))

paste("Prevelant Cases of NICM:", sum(NICM_tbl_BC$prevalent_status))
paste("Incident Cases of NICM:", sum(NICM_tbl_BC$incident_status))

cat("No of diabetes patients in whole sample:", sum(diabetes_tbl_BC$diabetes_status), "\n")
cat("No of hypertension patients in whole sample:", sum(hypertension_tbl_BC$hypertension_status), "\n")
cat("No of cholesterol patients in whole sample:", sum(cholesterol_tbl_BC$cholesterol_status), "\n")

```

```{r CMR_BC_sample_CVDs}

stroke_tbl_BC <- stroke_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
IHD_tbl_BC <- IHD_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
NICM_tbl_BC <- non_IHD_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids) 
pericard_tbl_BC <- pericardial_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
HF_tbl_BC <- HF_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
myocard_tbl_BC <- HA_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
diabetes_tbl_BC <- diabetes_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids) 
cholesterol_tbl_BC <- cholesterol_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
hypertension_tbl_BC <- hypertension_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
  
paste("Prevelant Cases of Pericardial Disease:", sum(pericard_tbl_BC$prevalent_status))
paste("Incident Cases of Pericardial Disease:", sum(pericard_tbl_BC$incident_status))

paste("Prevelant Cases of MYO INF:", sum(myocard_tbl_BC$prevalent_status))
paste("Incident Cases of MYO INF:", sum(myocard_tbl_BC$incident_status))

paste("Prevelant Cases of HF:", sum(HF_tbl_BC$prevalent_status))
paste("Incident Cases of HF:", sum(HF_tbl_BC$incident_status))

paste("Prevelant Cases of STROKE:", sum(stroke_tbl_BC$prevalent_status))
paste("Incident Cases of STROKE:", sum(stroke_tbl_BC$incident_status))

paste("Prevelant Cases of IHD:", sum(IHD_tbl_BC$prevalent_status))
paste("Incident Cases of IHD:", sum(IHD_tbl_BC$incident_status))

paste("Prevelant Cases of NICM:", sum(NICM_tbl_BC$prevalent_status))
paste("Incident Cases of NICM:", sum(NICM_tbl_BC$incident_status))

cat("No of diabetes patients in whole sample:", sum(diabetes_tbl_BC$diabetes_status), "\n")
cat("No of hypertension patients in whole sample:", sum(hypertension_tbl_BC$hypertension_status), "\n")
cat("No of cholesterol patients in whole sample:", sum(cholesterol_tbl_BC$cholesterol_status), "\n")
```

```{r CMR_BC_and_MRT_sample_CVDs}

stroke_tbl_BC <- stroke_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
IHD_tbl_BC <- IHD_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
NICM_tbl_BC <- non_IHD_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids) 
pericard_tbl_BC <- pericardial_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
HF_tbl_BC <- HF_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
myocard_tbl_BC <- HA_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
diabetes_tbl_BC <- diabetes_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids) 
cholesterol_tbl_BC <- cholesterol_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
hypertension_tbl_BC <- hypertension_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
  
paste("Prevelant Cases of Pericardial Disease:", sum(pericard_tbl_BC$prevalent_status))
paste("Incident Cases of Pericardial Disease:", sum(pericard_tbl_BC$incident_status))

paste("Prevelant Cases of MYO INF:", sum(myocard_tbl_BC$prevalent_status))
paste("Incident Cases of MYO INF:", sum(myocard_tbl_BC$incident_status))

paste("Prevelant Cases of HF:", sum(HF_tbl_BC$prevalent_status))
paste("Incident Cases of HF:", sum(HF_tbl_BC$incident_status))

paste("Prevelant Cases of STROKE:", sum(stroke_tbl_BC$prevalent_status))
paste("Incident Cases of STROKE:", sum(stroke_tbl_BC$incident_status))

paste("Prevelant Cases of IHD:", sum(IHD_tbl_BC$prevalent_status))
paste("Incident Cases of IHD:", sum(IHD_tbl_BC$incident_status))

paste("Prevelant Cases of NICM:", sum(NICM_tbl_BC$prevalent_status))
paste("Incident Cases of NICM:", sum(NICM_tbl_BC$incident_status))

cat("No of diabetes patients in whole sample:", sum(diabetes_tbl_BC$diabetes_status), "\n")
cat("No of hypertension patients in whole sample:", sum(hypertension_tbl_BC$hypertension_status), "\n")
cat("No of cholesterol patients in whole sample:", sum(cholesterol_tbl_BC$cholesterol_status), "\n")
```

### Demographics

```{r preprocessing_of_demographics_table}
tmp <- demographic_table %>% dplyr:: select(contains("status"))
factor_cols <- names(tmp)

tmp <- demographic_table %>% dplyr:: select(contains("alc"))
factor_cols <- c(factor_cols, names(tmp))

df1 <- demographic_table %>% dplyr:: select(contains("ethnicity"))
factor_cols <- c(factor_cols, names(df1))

# demographic_table <- demographic_table %>% mutate(across(all_of(factor_cols), factor))
demographic_table$recruitment_date <- ymd(demographic_table$recruitment_date)
demographic_table$sex <- factor(demographic_table$sex)
demographic_table$f.eid <- as.character(demographic_table$f.eid)

demographic_table$ethnicity_at_recruitment[demographic_table["ethnicity_at_recruitment"] == -1000] <- NA
demographic_table$ethnicity_at_calib_visit[demographic_table["ethnicity_at_calib_visit"] == -1000] <- NA
demographic_table$ethnicity_at_imaging_visit1[demographic_table["ethnicity_at_imaging_visit1"] == -1000] <- NA
```

```{r demographics_whole_sample}

# continuous <-select_if(demographic_table, is.numeric)
# summary(continuous)

# demographic_table_BC <- demographic_table %>% dplyr::filter(f.eid %in% BC_ids)
# continuous <-select_if(demographic_table_BC, is.numeric)
# summary(continuous)

# demographic_table_BC <- demographic_table %>% dplyr::filter(f.eid %in% non_BC_ids)
# continuous <-select_if(demographic_table_BC, is.numeric)
# summary(continuous)
# 
# demographic_table_BC <- demographic_table %>% dplyr::filter(f.eid %in% no_RT_and_BC_ids)
# continuous <-select_if(demographic_table_BC, is.numeric)
# summary(continuous)
# 
# demographic_table_BC <- demographic_table %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
# continuous <-select_if(demographic_table_BC, is.numeric)
# summary(continuous)

demographic_table_BC <- demographic_table %>% dplyr::filter(f.eid %in% cmr_ids)
continuous <-select_if(demographic_table_BC, is.numeric)
summary(continuous)

# library(ggplot2)
# ggplot(demographic_table, aes(x = age_at_recruitment)) +
#     geom_density(alpha = .2, fill = "#FF6666")
# 
# ggplot(demographic_table, aes(x = deprivation_index)) +
#     geom_density(alpha = .2, fill = "#FF6666")
# 
# ggplot(demographic_table, aes(x = education_score)) +
#     geom_density(alpha = .2, fill = "#FF6666")
# 
# ggplot(demographic_table, aes(x = mets_imaging_visit1)) +
#     geom_density(alpha = .2, fill = "#FF6666")
	
# options(scipen = 999)
# ggplot(factor, aes(x = sex)) +
#     geom_bar(alpha = .8, fill = "blue")

# prop.table(table(demographic_table$sex))
# prop.table(table(demographic_table$ethnicity_at_recruitment))
# prop.table(table(demographic_table$alc_intake_at_recruitment))
# prop.table(table(demographic_table$smoking_status_at_recruitment))

prop.table(table(demographic_table_BC$sex))
prop.table(table(demographic_table_BC$ethnicity_at_recruitment))
prop.table(table(demographic_table_BC$alc_intake_at_recruitment))
prop.table(table(demographic_table_BC$smoking_status_at_recruitment))

library(janitor)
tabyl(demographic_table_BC$sex, sort = TRUE)
tabyl(demographic_table_BC$ethnicity_at_recruitment, sort = TRUE)
# tabyl(demographic_table_BC$alc_intake_at_recruitment, sort = TRUE)
# tabyl(demographic_table_BC$smoking_status_at_recruitment, sort = TRUE)

```



### CMR measures

```{r}
# names(cmr_measures_tbl)

# ggplot(cmr_measures_tbl, aes(x = LVEDVI)) +
#     geom_density(alpha = .2, fill = "purple")
# ggplot(cmr_measures_tbl, aes(x = LV_mass2)) +
#     geom_density(alpha = .2, fill = "purple")
# ggplot(cmr_measures_tbl, aes(x = LVEF)) +
#     geom_density(alpha = .2, fill = "purple")
# ggplot(cmr_measures_tbl, aes(x = LVGFI)) +
#     geom_density(alpha = .2, fill = "purple")
# ggplot(cmr_measures_tbl, aes(x = GLS)) +
#     geom_density(alpha = .2, fill = "purple")

summary(cmr_measures_tbl)

BC_CMR_tbl <- cmr_measures_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
summary(BC_CMR_tbl)

BC_CMR_tbl <- cmr_measures_tbl %>% dplyr::filter(f.eid %in% cmr_bc_rt_ids)
summary(BC_CMR_tbl)

BC_CMR_tbl <- cmr_measures_tbl %>% dplyr::filter(f.eid %in% cmr_bc_ids)
summary(BC_CMR_tbl)

BC_CMR_tbl <- cmr_measures_tbl %>% dplyr::filter(f.eid %in% cmr_no_bc_ids)
summary(BC_CMR_tbl)

BC_CMR_tbl <- cmr_measures_tbl %>% dplyr::filter(f.eid %in% cmr_bc_but_no_mrt)
summary(BC_CMR_tbl)
```


## Linear Regression Models

### Filtering and Data Wrangling for BC patients
```{r LM_BC_vs_no_BC}

stroke_tbl_BC <- stroke_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, prevalent_status, incident_status) %>% rename(prev_status_stroke = prevalent_status,
                                                                     incident_status_stroke = incident_status)

IHD_tbl_BC <- IHD_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, prevalent_status, incident_status) %>% rename(prev_status_IHD = prevalent_status,
                                                                     incident_status_IHD = incident_status)

NICM_tbl_BC <- non_IHD_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, prevalent_status, incident_status) %>% rename(prev_status_NICM = prevalent_status,
                                                                     incident_status_NICM = incident_status)

pericard_tbl_BC <- pericardial_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, prevalent_status, incident_status) %>% rename(prev_status_pericard = prevalent_status,
                                                                     incident_status_pericard = incident_status)

HF_tbl_BC <- HF_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, prevalent_status, incident_status) %>% rename(prev_status_HF = prevalent_status,
                                                                     incident_status_HF = incident_status)

myocard_tbl_BC <- HA_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, prevalent_status, incident_status) %>% rename(prev_status_myocard_inf = prevalent_status,
                                                                     incident_status_myocard_inf = incident_status)

diabetes_tbl_BC <- diabetes_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, diabetes_status)

cholesterol_tbl_BC <- cholesterol_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, cholesterol_status)

hypertension_tbl_BC <- hypertension_tbl %>% # dplyr::filter(f.eid %in% BC_ids) %>% 
  dplyr::select(f.eid, hypertension_status)

df_list <- list(
                BC_tbl %>% select(-recruitment_date, -prevalent_status, -incident_status, -BC_diagnosis_date), 
                RT_tbl %>% select(-recruitment_date, -prevalent_status, -incident_status, -RT_session_date),
                demographic_table, diabetes_tbl_BC, hypertension_tbl_BC, cholesterol_tbl_BC,
                IHD_tbl_BC, NICM_tbl_BC, HF_tbl_BC, stroke_tbl_BC, pericard_tbl_BC, myocard_tbl_BC
                )

GLM_df <- df_list %>% reduce(full_join, by='f.eid')

tmp <- GLM_df %>% dplyr:: select(contains("status"))
factor_cols <- names(tmp)

tmp <- GLM_df %>% dplyr:: select(contains("alc"))
factor_cols <- c(factor_cols, names(tmp))

df1 <- GLM_df %>% dplyr:: select(contains("ethnicity"))
factor_cols <- c(factor_cols, names(df1))

GLM_df <- GLM_df %>% mutate(across(all_of(factor_cols), factor))
# data<-replace(df$Marks, df$Marks<0, 0)
GLM_df$recruitment_date <- ymd(GLM_df$recruitment_date)
GLM_df$sex <- factor(GLM_df$sex)
# nrow(GLM_df)
head(GLM_df, 20)
```
#### Linear Regression Model 

```{r}
GLM_df

# names(GLM_df)

test_df <- GLM_df %>% 
  select(f.eid, BC_status, prev_status_stroke, incident_status_stroke)

formula = incident_status_stroke ~ BC_status

model1 <- glm(formula, data = test_df, family = "binomial")
summary(model1)
```

### ...
```{r LM_BC_vs_no_BC_including_Covariates}

formula2 = incident_status_stroke ~ BC_status + 
  # age_at_recruitment + ethnicity_at_recruitment + 
  # deprivation_index + education_score + 
  diabetes_status + cholesterol_status + hypertension_status
model2 <- glm(formula2, data = GLM_df, family = "binomial")
summary(model2)


formula3 = incident_status_stroke ~ BC_status + 
  age_at_recruitment + ethnicity_at_recruitment +
  deprivation_index + education_score + alc_intake_at_recruitment +
  smoking_status_at_recruitment + mets_imaging_visit1 +
  diabetes_status + cholesterol_status + hypertension_status
model3 <- glm(formula3, data = GLM_df, family = "binomial")
summary(model3)
```

## Fine Gray Compete Risk Regressions

```{r}

```



