---
title: "Data Preprocessing for MRes Project"
author: "Gracia Andriamiadana"
date: "26/07/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(dplyr)
library(magrittr)
library(ggplot2)
```

## Load and edit data tables

```{r}
setwd("/Users/BHCadmin/Documents/mres_gracia/")
non_IHD_tbl = read.csv("non_IHD_patients_in_UKB.tsv", sep = "\t")

demographic_table <- read.csv("upd_demographics_table_UKB_data.tsv", header = T, sep = "\t")
diabetes_tbl = read.csv("diabetes_patients_in_UKB.tsv", sep = "\t")
stroke_tbl = read.csv("stroke_patients_in_UKB.tsv", sep = "\t")
hypertension_tbl = read.csv("hypertension_patients_in_UKB.tsv", sep = "\t")
cholesterol_tbl = read.csv("cholesterol_patients_in_UKB.tsv", sep = "\t")
IHD_tbl = read.csv("IHD_patients_in_UKB.tsv", sep = "\t")
non_IHD_tbl = read.csv("non_IHD_patients_in_UKB.tsv", sep = "\t")
HF_tbl = read.csv("heart_failure_patients_in_UKB.tsv", sep = "\t")
HA_tbl = read.csv("heart_attack_patients_in_UKB.tsv", sep = "\t")
pericardial_tbl <- read.csv("pericardial_patients_in_UKB.tsv", sep = "\t")
BC_tbl = read.csv("BC_patients_in_UKB.tsv", sep = "\t")
sum(BC_tbl$BC_status)

RT_tbl = read.csv("RT_patients_in_UKB.tsv", sep = "\t")
RT_tbl$RT_status <- NULL
RT_tbl$RT_status <- ifelse(RT_tbl$RT_date_icd10 == '' & RT_tbl$RT_date_opcs4 == '', 0, 1) 
# length(unique(RT_tbl$f.eid)) == nrow(RT_tbl) 
sum(RT_tbl$RT_status)

```


```{r}

nrow(diabetes_tbl)
diabetes_tbl <- diabetes_tbl %>% group_by(f.eid) %>%
  summarise(diabetes_status = max(diabetes_status, na.rm= TRUE),
            date_insulin_diabetes = (min(date_insulin_diabetes, na.rm= TRUE)),
            date_malnutrition_diabetes = (min(date_malnutrition_diabetes, na.rm= TRUE)),
            date_non_insulin_diabetes = (min(date_non_insulin_diabetes, na.rm = TRUE)),
            date_other_spec_diabetes = (min(date_other_spec_diabetes, na.rm = TRUE)),
            date_other_unspec_diabetes = (min(date_other_unspec_diabetes, na.rm = T))
            )
nrow(diabetes_tbl)
diabetes_tbl$date_insulin_diabetes <- ymd(diabetes_tbl$date_insulin_diabetes)
diabetes_tbl$date_malnutrition_diabetes <- ymd(diabetes_tbl$date_malnutrition_diabetes)
diabetes_tbl$date_non_insulin_diabetes <- ymd(diabetes_tbl$date_non_insulin_diabetes)
diabetes_tbl$date_other_spec_diabetes <- ymd(diabetes_tbl$date_other_spec_diabetes)
diabetes_tbl$date_other_unspec_diabetes <- ymd(diabetes_tbl$date_other_unspec_diabetes)

names(hypertension_tbl)
hypertension_tbl <- hypertension_tbl %>% group_by(f.eid) %>%
  summarise(date_hypertension = min(date_hypertension, na.rm = T), 
            hypertension_status = max(hypertension_status)
  )
hypertension_tbl$date_hypertension <- ymd(hypertension_tbl$date_hypertension)

names(cholesterol_tbl)
cholesterol_tbl <- cholesterol_tbl %>% group_by(f.eid) %>%
  summarise(date_lipidaemia = min(date_lipidaemia, na.rm = T),
            cholesterol_status = max(cholesterol_status)
  )
cholesterol_tbl$date_lipidaemia <- ymd(cholesterol_tbl$date_lipidaemia)


names(IHD_tbl)
IHD_tbl <- IHD_tbl %>% group_by(f.eid) %>% 
  summarise(IHD_status = max(IHD_status,na.rm = T),
            date_angina_pec = min(date_angina_pec,na.rm = T),
            date_chronic_iscHD = min(date_chronic_iscHD, na.rm = T),
            date_other_iscHD = min(date_other_iscHD, na.rm = T)
            )
IHD_tbl$date_angina_pec <- ymd(IHD_tbl$date_angina_pec)
IHD_tbl$date_chronic_iscHD <- ymd(IHD_tbl$date_chronic_iscHD)
IHD_tbl$date_other_iscHD <- ymd(IHD_tbl$date_other_iscHD)


stroke_tbl <- stroke_tbl %>% group_by(f.eid) %>%
  summarise(Stroke_Status = max(Stroke_Status, na.rm = T),
            date_stroke = max(date_stroke, na.rm = T), 
            date_stroke_42006 = max(date_stroke_42006, na.rm = T), 
            date_isch_stroke_42008 = max(date_isch_stroke_42008, na.rm = T),
            date_cerebral_infarction = max(date_cerebral_infarction, na.rm = T), 
            date_intracerebral_haemorrhage = max(date_intracerebral_haemorrhage, na.rm = T),
            date_intracerebral_haemorrhage_42010 = max(date_intracerebral_haemorrhage_42010, na.rm = T),
            date_other_intracerebral_haemorrhage = max(date_other_intracerebral_haemorrhage, na.rm = T))

stroke_tbl$date_stroke <- ymd(stroke_tbl$date_stroke)
stroke_tbl$date_stroke_42006 <- ymd(stroke_tbl$date_stroke_42006)
stroke_tbl$date_isch_stroke_42008 <- ymd(stroke_tbl$date_isch_stroke_42008)
stroke_tbl$date_cerebral_infarction <- ymd(stroke_tbl$date_cerebral_infarction)
stroke_tbl$date_intracerebral_haemorrhage <- ymd(stroke_tbl$date_intracerebral_haemorrhage)
stroke_tbl$date_intracerebral_haemorrhage_42010 <- ymd(stroke_tbl$date_intracerebral_haemorrhage_42010)
stroke_tbl$date_other_intracerebral_haemorrhage <- ymd(stroke_tbl$date_other_intracerebral_haemorrhage)


names(HF_tbl)
HF_tbl <- HF_tbl %>% group_by(f.eid) %>%
  summarise(HF_status = max(HF_status),
            date_HF = min(date_HF, na.rm = T))
HF_tbl$date_HF <- ymd(HF_tbl$date_HF)

names(non_IHD_tbl)

non_IHD_tbl <- non_IHD_tbl %>% group_by(f.eid) %>% 
  summarise(non_IHD_status = max(non_IHD_status,na.rm = T),
            date_cardiomyopathy = min(date_cardiomyopathy, na.rm = T),
            date_cardiomyopathy_elsewhere = min(date_cardiomyopathy_elsewhere, na.rm = T),
            date_hypertensive_HD = min(date_hypertensive_HD, na.rm = T),
            date_hypertensive_HD_and_RD = min(date_hypertensive_HD_and_RD, na.rm = T),
            )
non_IHD_tbl$date_cardiomyopathy <- ymd(non_IHD_tbl$date_cardiomyopathy)
non_IHD_tbl$date_cardiomyopathy_elsewhere <- ymd(non_IHD_tbl$date_cardiomyopathy_elsewhere)
non_IHD_tbl$date_hypertensive_HD <- ymd(non_IHD_tbl$date_hypertensive_HD)
non_IHD_tbl$date_hypertensive_HD_and_RD <- ymd(non_IHD_tbl$date_hypertensive_HD_and_RD)

names(HA_tbl)

pericardial_tbl <- pericardial_tbl %>% group_by(f.eid) %>%
  summarise(pericard_status = max(pericard_status),
            pericard_date = min(pericard_date, na.rm = T))

pericardial_tbl$pericard_date <- ymd(pericardial_tbl$pericard_date)

HA_tbl <- HA_tbl %>% group_by(f.eid) %>%
  summarise(HA_status = max(HA_status),
            date_acute_HA = min(date_acute_HA, na.rm = T),
            date_subseq_HA = min(date_subseq_HA, na.rm = T),
            date_complications_after_HA = min(date_complications_after_HA, na.rm = T),
            date_myo_infarction_HA = min(date_myo_infarction_HA, na.rm = T),
            )
HA_tbl$date_acute_HA <- ymd(HA_tbl$date_acute_HA)
HA_tbl$date_subseq_HA <- ymd(HA_tbl$date_subseq_HA)
HA_tbl$date_complications_after_HA <- ymd(HA_tbl$date_complications_after_HA)
HA_tbl$date_myo_infarction_HA <- ymd(HA_tbl$date_myo_infarction_HA)


#put all data frames into list
df_list <- list(demographic_table, 
                diabetes_tbl, hypertension_tbl, cholesterol_tbl,
                IHD_tbl, non_IHD_tbl, HF_tbl, stroke_tbl, pericardial_tbl, HA_tbl)

#merge all data frames in list
sample_df <- df_list %>% reduce(full_join, by='f.eid')
head(sample_df, 10)

length(unique(sample_df$f.eid)) == nrow(sample_df)
write.table(diabetes_tbl, file = "summarised_diabetes_patients_in_UKB.tsv", sep = "\t")
write.table(hypertension_tbl, file = "summarised_hypertension_patients_in_UKB.tsv", sep = "\t")
write.table(cholesterol_tbl, file = "summarised_cholesterol_patients_in_UKB.tsv", sep = "\t")
write.table(IHD_tbl, file = "summarised_IHD_patients_in_UKB.tsv", sep = "\t")
write.table(non_IHD_tbl, file = "summarised_non_IHD_patients_in_UKB.tsv", sep = "\t")
write.table(HF_tbl, file = "summarised_heart_failure_patients_in_UKB.tsv", sep = "\t")
write.table(HA_tbl, file = "summarised_heart_attack_patients_in_UKB.tsv", sep = "\t")
write.table(pericardial_tbl, file = "summarised_pericardial_patients_in_UKB.tsv", sep = "\t")
write.table(stroke_tbl, file = "summarised_stroke_patients_in_UKB.tsv", sep = "\t")

write.table(sample_df, file = "analysis_sample_UKB_patients.tsv", sep = "\t")

```


```{r relabelling_cases}

BC_tbl = read.csv("BC_patients_in_UKB.tsv", sep = "\t")
sum(BC_tbl$BC_status)

RT_tbl = read.csv("RT_patients_in_UKB.tsv", sep = "\t")
RT_tbl$RT_status <- NULL
RT_tbl$RT_status <- ifelse(RT_tbl$RT_date_icd10 == '' & RT_tbl$RT_date_opcs4 == '', 0, 1)
sum(RT_tbl$RT_status)

BC_tbl[(BC_tbl == "")] <- "2050-12-12"
RT_tbl[(RT_tbl == "")] <- "2050-12-12"
stroke_tbl[is.na(stroke_tbl)] <- "2050-12-12"
IHD_tbl[is.na(IHD_tbl)] <- "2050-12-12"
non_IHD_tbl[is.na(non_IHD_tbl)] <- "2050-12-12"
pericardial_tbl[is.na(pericardial_tbl)] <- "2050-12-12"
HA_tbl[is.na(HA_tbl)] <- "2050-12-12"
HF_tbl[is.na(HF_tbl)] <- "2050-12-12"

diabetes_tbl[is.na(diabetes_tbl)] <- "2050-12-12"
hypertension_tbl[is.na(hypertension_tbl)] <- "2050-12-12"
cholesterol_tbl[is.na(cholesterol_tbl)] <- "2050-12-12"

# t0<- diabetes_tbl %>% gather(key, value, -c(f.eid, diabetes_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, diabetes_status, date) %>%
#   group_by(f.eid, diabetes_status) %>% summarise(minDate= min(date))

# t0<- hypertension_tbl %>% gather(key, value, -c(f.eid, hypertension_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, hypertension_status, date) %>%
#   group_by(f.eid, hypertension_status) %>% summarise(minDate= min(date))

t0<- cholesterol_tbl %>% gather(key, value, -c(f.eid, cholesterol_status)) %>%
  mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
  select(f.eid, cholesterol_status, date) %>%
  group_by(f.eid, cholesterol_status) %>% summarise(minDate= min(date))

# t0<- BC_tbl %>% gather(key, value, -c(f.eid, BC_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, BC_status, date) %>%
#   group_by(f.eid, BC_status) %>% summarise(minDate= min(date))

# t0<- RT_tbl %>% gather(key, value, -c(f.eid, RT_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, RT_status, date) %>%
#   group_by(f.eid, RT_status) %>% summarise(minDate= min(date))

# t0<- stroke_tbl %>% gather(key, value, -c(f.eid, Stroke_Status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, Stroke_Status, date) %>%
#   group_by(f.eid, Stroke_Status) %>% summarise(minDate= min(date))

# t0<- IHD_tbl %>% gather(key, value, -c(f.eid, IHD_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, IHD_status, date) %>%
#   group_by(f.eid, IHD_status) %>% summarise(minDate= min(date))

# t0<- non_IHD_tbl %>% gather(key, value, -c(f.eid, non_IHD_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, non_IHD_status, date) %>%
#   group_by(f.eid, non_IHD_status) %>% summarise(minDate= min(date, na.rm = F))

# t0<- HF_tbl %>% gather(key, value, -c(f.eid, HF_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, HF_status, date) %>%
#   group_by(f.eid, HF_status) %>% summarise(minDate= min(date))

# t0<- HA_tbl %>% gather(key, value, -c(f.eid, HA_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, HA_status, date) %>%
#   group_by(f.eid, HA_status) %>% summarise(minDate= min(date))

# t0<- pericardial_tbl %>% gather(key, value, -c(f.eid, pericard_status)) %>%
#   mutate(date= str_sub(value, 1, 10) %>% ymd()) %>%
#   select(f.eid, pericard_status, date) %>%
#   group_by(f.eid, pericard_status) %>% summarise(minDate= min(date))

t0$minDate <- ymd(t0$minDate)
t0$minDate[t0$minDate == "2050-12-12"] <- NA
View(t0)

temp_df <- sample_df %>% select(f.eid, recruitment_date) 
temp_df$recruitment_date <- ymd(temp_df$recruitment_date)

t2 <- full_join(temp_df, t0, by = "f.eid") %>% 
  mutate(prevalent_status = ifelse(minDate <= recruitment_date,1,0),
         incident_status = ifelse(minDate > recruitment_date, 1, 0))

t2$prevalent_status <- replace(t2$prevalent_status,is.na(t2$prevalent_status),0)
t2$incident_status <- replace(t2$incident_status,is.na(t2$incident_status),0)

# updated_diabetes_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))
# updated_hypertension_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))
updated_cholesterol_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))

updated_pericardial_tbl <- updated_pericardial_tbl %>% rename(pericard_diagnosis_date = minDate)
updated_stroke_tbl <- updated_stroke_tbl %>% rename(stroke_diagnosis_date = minDate, 
                                                    stroke_status = Stroke_Status)
updated_IHD_tbl <- updated_IHD_tbl %>% rename(IHD_diagnosis_date = minDate)
updated_non_IHD_tbl <- updated_non_IHD_tbl %>% rename(non_IHD_diagnosis_date = minDate)
updated_HF_tbl <- updated_HF_tbl %>% rename(HF_date = minDate)
updated_HA_tbl <- updated_HA_tbl %>% rename(HA_date = minDate)
updated_RT_tbl <- updated_RT_tbl %>% rename(RT_session_date = minDate)
updated_BC_tbl <- updated_BC_tbl %>% rename(BC_diagnosis_date = minDate)

updated_diabetes_tbl <- updated_diabetes_tbl %>% rename(diabetes_diagnosis_date = minDate)
updated_hypertension_tbl <- updated_hypertension_tbl %>% rename(hypertension_diagnosis_date = minDate)
updated_cholesterol_tbl <- updated_cholesterol_tbl %>% rename(cholesterol_diagnosis_date = minDate)


# df_list <- list(demographic_table, 
#                 updated_diabetes_tbl %>%select(-recruitment_date), 
#                 updated_hypertension_tbl %>%select(-recruitment_date), 
#                 updated_cholesterol_tbl %>%select(-recruitment_date),
#                 updated_IHD_tbl %>%select(-recruitment_date), 
#                 updated_non_IHD_tbl %>%select(-recruitment_date), 
#                 updated_HF_tbl %>%select(-recruitment_date), 
#                 updated_stroke_tbl %>%select(-recruitment_date), 
#                 updated_pericardial_tbl %>%select(-recruitment_date), 
#                 updated_HA_tbl %>%select(-recruitment_date)
#                 )
# 
# #merge all data frames in list
# updated_sample_df <- df_list %>% reduce(full_join, by='f.eid')
# View(head(updated_sample_df, 10))


# updated_pericardial_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))
# updated_stroke_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))
# updated_IHD_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))
# updated_non_IHD_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))
# updated_HF_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))
# updated_HA_tbl <- tidyr::replace_na(t2, list(prevalent_status=0, incident_status=0))

```


<!-- ```{r} -->
<!-- write.table(updated_diabetes_tbl, file = "updated_diabetes_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_cholesterol_tbl, file = "updated_cholesterol_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_hypertension_tbl, file = "updated_hypertension_tbl.tsv", sep = "\t") -->

<!-- write.table(updated_IHD_tbl, file = "updated_IHD_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_non_IHD_tbl, file = "updated_non_IHD_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_HF_tbl, file = "updated_HF_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_HA_tbl, file = "updated_HA_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_pericardial_tbl, file = "updated_pericardial_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_stroke_tbl, file = "updated_stroke_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_BC_tbl, file = "updated_BC_tbl.tsv", sep = "\t") -->
<!-- write.table(updated_RT_tbl, file = "updated_RT_tbl.tsv", sep = "\t") -->
<!-- ``` -->


```{r}
diabetes_tbl
cholesterol_tbl
IHD_tbl %>% filter(IHD_status >0)
non_IHD_tbl %>% filter(non_IHD_status >0)
pericardial_tbl %>% filter(pericard_status >0)
HA_tbl
HF_tbl

```

```{r demographics_whole_sample}

# calculate average and median age of whole sample
mean(demographic_table$age_at_recruitment, na.rm = T)
median(demographic_table$age_at_recruitment, na.rm = T)

table(demographic_table$ethnicity_at_recruitment)

mean(demographic_table$deprivation_index, na.rm = T)
median(demographic_table$deprivation_index, na.rm = T)

(table(demographic_table$alc_intake_at_recruitment))

(table(demographic_table$smoking_status_at_recruitment))
max(table(demographic_table$smoking_status_at_recruitment))

mean(demographic_table$mets_imaging_visit1, na.rm = T)
median(demographic_table$mets_imaging_visit1, na.rm = T)
```

```{r}
head(IHD_tbl)
head(sample_df)
stroke_tbl
names(sample_df)
View(stroke_tbl)

### read more about gather function!
t0<- stroke_tbl %>% gather(key, value, -c(f.eid, Stroke_Status)) %>% 
                             mutate(date= str_sub(value, 1, 10) %>% ymd())
t0


t1<- t0 %>% group_by(f.eid, Stroke_Status, .drop = T) %>% summarise(minDate= min(date, na.rm=TRUE))
t1$minDate <- ymd(t1$minDate)

t1                                  

View(t1)

temp_df <- sample_df %>% select(f.eid, recruitment_date) 
temp_df$recruitment_date <- ymd(temp_df$recruitment_date)
temp_df
t2 <- full_join(temp_df, t1)
t2
t2 %>% filter(minDate <= recruitment_date)

t3 <- t2 %>% mutate(prevalent_status = minDate <= recruitment_date,
              incident_status = minDate > recruitment_date)
head(t3)
```





```{r}
names(IHD_tbl)
head(IHD_tbl)

select(IHD_tbl, matches("date"))

test_df <- IHD_tbl%>% select(matches("date")) 
IHD_tbl %>% filter(names(test_df) < sample_df$recruitment_date)
```

```{r whole_sample}
cat("No of diabetes patients in whole sample:", sum(sample_df$diabetes_status), "\n")
cat("No of hypertension patients in whole sample:", sum(sample_df$hypertension_status), "\n")
cat("No of cholesterol patients in whole sample:", sum(sample_df$cholesterol_status), "\n")

names(stroke_tbl)
cholesterol_at_baseline = sample_df %>% filter(date_stroke < recruitment_date) 
sample_df %>% filter(date_cerebral_infarction > recruitment_date)
sum(cholesterol_at_baseline$cholesterol_status)
ids_cholesterol_at_baseline <- cholesterol_at_baseline$f.eid

```

```{r BC_sample}

BC_ids <- BC_tbl %>% dplyr::filter(BC_status == 1) %>% select(f.eid)
nrow(BC_ids)
BC_ids <- as.vector(BC_ids$f.eid)


dim(diabetes_tbl)
diabetes_tbl_BC <- diabetes_tbl %>% dplyr::filter(f.eid %in% BC_ids)
dim(diabetes_tbl)

test_df <- diabetes_tbl_BC %>% group_by(f.eid) %>% 
  summarise(diabetes_status = max(diabetes_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 

cat("No of diabetes patients in BC sample:", sum(test_df$diabetes_status), "\n")

stroke_tbl_BC <- stroke_tbl %>% dplyr::filter(f.eid %in% BC_ids)

test_df <- stroke_tbl_BC %>% group_by(f.eid) %>% 
  summarise(Stroke_Status = max(Stroke_Status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of Stroke patients in BC sample:", sum(test_df$Stroke_Status), "\n")

hypertension_tbl_BC <- hypertension_tbl %>% dplyr::filter(f.eid %in% BC_ids)

test_df <- hypertension_tbl_BC %>% group_by(f.eid) %>% 
  summarise(hypertension_status = max(hypertension_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of hypertension patients in BC sample:", sum(test_df$hypertension_status), "\n")

cholesterol_tbl_BC <- cholesterol_tbl %>% dplyr::filter(f.eid %in% BC_ids)

test_df <- cholesterol_tbl_BC %>% group_by(f.eid) %>% 
  summarise(cholesterol_status = max(cholesterol_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of cholesterol patients in BC sample:", sum(test_df$cholesterol_status), "\n")

IHD_tbl_BC <- IHD_tbl %>% dplyr::filter(f.eid %in% BC_ids)

test_df <- IHD_tbl_BC %>% group_by(f.eid) %>% 
  summarise(IHD_status = max(IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of IHD patients in BC sample:", sum(test_df$IHD_status), "\n")

non_IHD_tbl_BC <- non_IHD_tbl %>% dplyr::filter(f.eid %in% BC_ids)

test_df <- non_IHD_tbl_BC %>% group_by(f.eid) %>% 
  summarise(non_IHD_status = max(non_IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of non IHD patients in BC sample:", sum(test_df$non_IHD_status), "\n")

HF_tbl_BC <- HF_tbl %>% dplyr::filter(f.eid %in% BC_ids)

test_df <- HF_tbl_BC %>% group_by(f.eid) %>% 
  summarise(HF_status = max(HF_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HF patients in BC sample:", sum(test_df$HF_status), "\n")

HA_tbl_BC <- HA_tbl %>% dplyr::filter(f.eid %in% BC_ids)

test_df <- HA_tbl_BC %>% group_by(f.eid) %>% 
  summarise(HA_status = max(HA_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HA patients in BC sample:", sum(test_df$HA_status), "\n")

```

```{r non_BC_sample}
non_BC_ids <- BC_tbl %>% dplyr::filter(BC_status == 0) %>% select(f.eid)
nrow(non_BC_ids)
non_BC_ids <- as.vector(non_BC_ids$f.eid)


dim(diabetes_tbl)
diabetes_tbl_no_BC <- diabetes_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))
dim(diabetes_tbl_no_BC)

test_df <- diabetes_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(diabetes_status = max(diabetes_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 

cat("No of diabetes patients in no BC sample:", sum(test_df$diabetes_status), "\n")

stroke_tbl_no_BC <- stroke_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))

test_df <- stroke_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(Stroke_Status = max(Stroke_Status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of Stroke patients in no BC sample:", sum(test_df$Stroke_Status), "\n")

hypertension_tbl_no_BC <- hypertension_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))

test_df <- hypertension_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(hypertension_status = max(hypertension_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of hypertension patients in no BC sample:", sum(test_df$hypertension_status), "\n")

cholesterol_tbl_no_BC <- cholesterol_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))

test_df <- cholesterol_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(cholesterol_status = max(cholesterol_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of cholesterol patients in no BC sample:", sum(test_df$cholesterol_status), "\n")

IHD_tbl_no_BC <- IHD_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))

test_df <- IHD_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(IHD_status = max(IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of IHD patients in no BC sample:", sum(test_df$IHD_status), "\n")

non_IHD_tbl_no_BC <- non_IHD_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))

test_df <- non_IHD_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(non_IHD_status = max(non_IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of non IHD patients in no BC sample:", sum(test_df$non_IHD_status), "\n")

HF_tbl_no_BC <- HF_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))

test_df <- HF_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(HF_status = max(HF_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HF patients in no BC sample:", sum(test_df$HF_status), "\n")

HA_tbl_no_BC <- HA_tbl %>% dplyr::filter((f.eid %in% non_BC_ids))

test_df <- HA_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(HA_status = max(HA_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HA patients in no BC sample:", sum(test_df$HA_status), "\n")

```


```{r HIER}
RT_ids <- RT_tbl %>% dplyr::filter(RT_status == 1) %>% select(f.eid)
nrow(RT_ids)

RT_and_BC_ids <- intersect(as.vector(BC_ids), as.vector(RT_ids$f.eid))
length(RT_and_BC_ids)

no_RT_ids <- RT_tbl %>% dplyr::filter(RT_status == 0) %>% select(f.eid)
no_RT_and_BC_ids <- intersect(as.vector(BC_ids), as.vector(no_RT_ids$f.eid))
length(no_RT_and_BC_ids)
```

```{r BC_and_RT_sample}

dim(diabetes_tbl)
diabetes_tbl_RT_BC <- diabetes_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)
dim(diabetes_tbl)

test_df <- diabetes_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(diabetes_status = max(diabetes_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 

cat("No of diabetes patients in RT and BC sample:", sum(test_df$diabetes_status), "\n")

stroke_tbl_RT_BC <- stroke_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)

test_df <- stroke_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(Stroke_Status = max(Stroke_Status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of Stroke patients in RT and BC sample:", sum(test_df$Stroke_Status), "\n")

hypertension_tbl_RT_BC <- hypertension_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)

test_df <- hypertension_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(hypertension_status = max(hypertension_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of hypertension patients in RT and BC sample:", sum(test_df$hypertension_status), "\n")

cholesterol_tbl_RT_BC <- cholesterol_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)

test_df <- cholesterol_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(cholesterol_status = max(cholesterol_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of cholesterol patients in RT and BC sample:", sum(test_df$cholesterol_status), "\n")

IHD_tbl_RT_BC <- IHD_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)

test_df <- IHD_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(IHD_status = max(IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of IHD patients in RT and BC sample:", sum(test_df$IHD_status), "\n")

non_IHD_tbl_RT_BC <- non_IHD_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)

test_df <- non_IHD_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(non_IHD_status = max(non_IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of non IHD patients in RT and BC sample:", sum(test_df$non_IHD_status), "\n")

HF_tbl_RT_BC <- HF_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)

test_df <- HF_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(HF_status = max(HF_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HF patients in RT and BC sample:", sum(test_df$HF_status), "\n")

HA_tbl_RT_BC <- HA_tbl %>% dplyr::filter(f.eid %in% RT_and_BC_ids)

test_df <- HA_tbl_RT_BC %>% group_by(f.eid) %>% 
  summarise(HA_status = max(HA_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HA patients in BC sample:", sum(test_df$HA_status), "\n")

```


```{r no_BC_and_MRT_sample}

dim(diabetes_tbl)
diabetes_tbl_no_BC <- diabetes_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))
dim(diabetes_tbl_no_BC)

test_df <- diabetes_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(diabetes_status = max(diabetes_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 

cat("No of diabetes patients in no RT_and_BC sample:", sum(test_df$diabetes_status), "\n")

stroke_tbl_no_BC <- stroke_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))

test_df <- stroke_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(Stroke_Status = max(Stroke_Status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of Stroke patients in no RT & BC sample:", sum(test_df$Stroke_Status), "\n")

hypertension_tbl_no_BC <- hypertension_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))

test_df <- hypertension_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(hypertension_status = max(hypertension_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of hypertension patients in no RT & BC sample:", sum(test_df$hypertension_status), "\n")

cholesterol_tbl_no_BC <- cholesterol_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))

test_df <- cholesterol_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(cholesterol_status = max(cholesterol_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of cholesterol patients in no RT & BC sample:", sum(test_df$cholesterol_status), "\n")

IHD_tbl_no_BC <- IHD_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))

test_df <- IHD_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(IHD_status = max(IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of IHD patients in no RT & BC sample:", sum(test_df$IHD_status), "\n")

non_IHD_tbl_no_BC <- non_IHD_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))

test_df <- non_IHD_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(non_IHD_status = max(non_IHD_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of non IHD patients in no RT & BC sample:", sum(test_df$non_IHD_status), "\n")

HF_tbl_no_BC <- HF_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))

test_df <- HF_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(HF_status = max(HF_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HF patients in no RT & BC sample:", sum(test_df$HF_status), "\n")

HA_tbl_no_BC <- HA_tbl %>% dplyr::filter((f.eid %in% no_RT_and_BC_ids))

test_df <- HA_tbl_no_BC %>% group_by(f.eid) %>% 
  summarise(HA_status = max(HA_status, na.rm= TRUE))
# length(unique(test_df$f.eid)) == nrow(test_df) 
cat("No of HA patients in no RT & BC sample:", sum(test_df$HA_status), "\n")

```

```{r}
sample_df %>% filter(date_acute_HA < recruitment_date)
sample_df %>% filter(date_acute_HA >= recruitment_date)

```

```{r experimenting, include=FALSE}
IHD_tbl$date_angina_pec <- as.POSIXct( (IHD_tbl$date_angina_pec),
                                       format = "%Y-%m-%d %H:%M:%S", tz = "GMT")
IHD_tbl$date_other_iscHD <- as.POSIXct( (IHD_tbl$date_other_iscHD),
                                       format = "%Y-%m-%d %H:%M:%S", tz = "GMT")
IHD_tbl$date_chronic_iscHD <- as.POSIXct( (IHD_tbl$date_chronic_iscHD),
                                       format = "%Y-%m-%d %H:%M:%S", tz = "GMT")
IHD_tbl

```

## Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
?as.POSIXct
```
